apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: engine
    app.kubernetes.io/component: engine
    app.kubernetes.io/instance: engine
    app.kubernetes.io/name: engine
    app.kubernetes.io/part-of: engine
    app.openshift.io/runtime: python
  name: engine
  namespace: sasya-chikitsa
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      app: engine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: engine
        app.kubernetes.io/component: engine
        app.kubernetes.io/name: engine
        deployment: engine
    spec:
      containers:
      - image: quay.io/rajivranjan/engine:latest
        imagePullPolicy: Always
        name: engine
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
